### ISSUE TITLE
Support for different caching backends

### ISSUE THREAD

**Issue by yagooar** [adamcooke/vat-rates#22]
It would be nice to remove the hard dependency on the file system in order to cache the json results. If you are interested, I could open a PR.

Before I write the code, I'd like to know if you are interested and what requirements you have. My idea would be to allow switching in a cache backend compatible with the `ActiveSupport::Cache::Store` interface, with a file system fallback.

**Comment by adamcooke** [comment]
I assume this is a request for the JSON VAT gem (https://github.com/adamcooke/json-vat) rather than this repository?

This seemed like a good idea so I've done ahead and added it. You can read more information about it in the README [here](https://github.com/adamcooke/json-vat#caching). I hope that helps.

**Comment by yagooar** [comment]
Sorry, I must have had both tabs open. And thanks for adding it to the gem, that's very cool!
