### ISSUE TITLE
SSL certificate error

### ISSUE THREAD

**Issue by dianacrey** [adamcooke/vat-rates#37]
It looks like the SSL certificate of https://jsonvat.com expired today: ‎30 ‎October ‎2018 01:49:26 AM

Could you fix this? Thanks

**Comment by mikebarlow** [comment]
Came here to post this issue but someone beat me to it. 

May want to look at something like LetsEncrypt can just set it up with the auto renew script and pretty much forget about it.

**Comment by dannyvankooten** [comment]
Hey everyone, FYI: it looks like @adamcooke is short on time these months, so I forked this repository to [ibericode/vat-rates](https://github.com/ibericode/vat-rates) and implemented some changes or improvements.

The JSON resource now lives directly in the repository so that we can benefit from GitHub's CDN and won't have to worry about SSL certificate or availability as much.

**Comment by Mark-H** [comment]
Doesn't look like the structure of the JSON is the same in that fork, so anyone considering switching should make note of that.

**Comment by Mark-H** [comment]
The SSL certificate issue on jsonvat.com was also resolved and now seems to be using lets encrypt.
